### PR TITLE
New TPR service list component with search

### PR DESCRIPTION
**Pull request by dragos-dumi-ibm**
# [PLAENH-185](https://helsinkisolutionoffice.atlassian.net/browse/PLAENH-185)
[UHF-7656](https://helsinkisolutionoffice.atlassian.net/browse/UHF-7656)

New TPR service list component with search

## What was done
More details at
https://helsinkisolutionoffice.atlassian.net/browse/PLAENH-185

## How to install
* Update the module with this PR https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/128
* Update the theme with PR 
* Run `make drush-updb drush-cr`
* Run `PARTIAL_MIGRATE=1 drush migrate:import tpr_service --no-progress`

## How to test
Add to a page that has paragraphs the new component "Service List Search"
Configure the component with using service_id and/or specific services

* [ ] The page used in installation should have a listing that looks like this https://app.abstract.com/share/505f9e4a-9291-48ca-9bcc-4f38a7bc3e36?collectionId=4d66b7af-5224-4b71-8d19-a4df8af377c0&collectionLayerId=0d3595f3-dc9c-4c8e-8dc3-e7c5c09ac932&present=true&preview=false&sha=bf449ac81535612facaff26e7355b3b354509124
* [ ] Search should work against title, short desc and name synonyms
* [ ] Services teasers should use the imported translations

## Other PRs
* https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/128

[PLAENH-185]: https://helsinkisolutionoffice.atlassian.net/browse/PLAENH-185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UHF-7656]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-7656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tuutti** [comment]
The search bar seems to work when I open the Views display manually (`/admin/structure/views/view/service_list/edit/block_1`), but not on actual paragraph page:

image

image

**Comment by dragos-dumi-ibm** [comment]
@tuutti 
If there are less than 5 services, the total count and search bar won't show (it was a requirement) This condition is done only for the front-end theme, that's why is different in views preview in admin.

**Comment by tuutti** [comment]
Ah, makes sense. Seems to work now

**Comment by dragos-dumi-ibm** [comment]
@tuutti I've found the issue you mentioned on slack with the uncachable. was due to this filter in views

https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/407/commits/b191aefb93a638f5623129e2077675b3d54c9b6d

**Comment by juho-lehmonen** [comment]
Codewise this looks good and is working as described. We're asking for feedback from the UX team and Aleksi about how the paragraph works on the editor side (might need some additional help texts and a better widget for the service grouping IDs). I'll comment here as soon as possible if something needs to be fixed.

**Review by juho-lehmonen — CHANGES_REQUESTED** [review]
If you edit a service with the "Override: name" field, the title is correctly changed in the search results, but it's not included in the search. If you try searching with the overridden name, you can't find the service.

**Comment by dragos-dumi-ibm** [comment]
@juho-lehmonen thanks for the review. We've included also the override title in the search
+ we've updated the field label and description as commented yesterday on PLAENH-185

**Review by juho-lehmonen — APPROVED** [review]
This looks good, thanks for the fixes! This can be merged after the conflicts have been resolved.

**Comment by dragos-dumi-ibm** [comment]
@juho-lehmonen the conflicts have been fixed.

**Comment by juho-lehmonen** [comment]
> @juho-lehmonen the conflicts have been fixed.

Great, I'll merge this.

**Pull request merged**
